# Continuous Integration recipes
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        zig-version: ['0.13.0', '0.14.0', '0.14.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check formatting
        run: zig build check-fmt

      - name: Run tests
        run: zig build test

      - name: Build application
        run: zig build

  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: '0.14.1'

      - name: Build release
        run: zig build -Doptimize=ReleaseFast

      - name: Generate documentation
        run: make generate

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zstd-live-${{ github.sha }}
          path: |
            zig-out/bin/zstd-live
            dist/
          retention-days: 30
